<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppMessageRepository extends EntityRepository
{
    public function findOneToShow($user)
    {
        $qb  = $this->createQueryBuilder('am');
        $qb2 = $this->_em->getRepository('VocalizrAppBundle:AppMessageRead')->createQueryBuilder('amr');
        $qb2->select('identity(amr.app_message)')
            ->where('amr.user_info = :user')
            ->andWhere('amr.closed_at is not null');

        $qb->select('am')
          ->where(
              $qb->expr()->orX(
                  $qb->expr()->isNull('am.expire_at'),
                  $qb->expr()->gte('am.expire_at', ':now')
              )
          )
          ->andWhere($qb->expr()->notIn('am.id', $qb2->getDQL()))
          ->orderBy('am.created_at', 'asc')
          ->setMaxResults(1);

        $params = [
            ':user' => $user,
            ':now'  => date('Y-m-d H:i:s'),
        ];
        $qb->setParameters($params);
        $query = $qb->getQuery();

        $results = $query->execute();
        return $results ? $results[0] : null;
    }
}
