<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AudioPlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioPlayRepository extends DocumentRepository
{
}