<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * AudioLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioLikeRepository extends DocumentRepository
{
}