<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{
    /**
     * @param $user
     *
     * @return array
     */
    public function getLanguagesByUser($user)
    {
        return $this->createQueryBuilder('l')
            ->join('l.userLanguages', 'ul')
            ->where('ul.userInfo = :user')
            ->setParameter('user', $user)
            ->getQuery()->getResult();
    }
}
