<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\QueryException;
use Vocalizr\AppBundle\Entity\UserInfo;

/**
 * ProjectBidLogRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ProjectBidLogRepository extends EntityRepository
{
    /**
     * @param UserInfo $user
     *
     * @return int|null
     */
    public function countUserBidsThisMonth(UserInfo $user)
    {
        $firstDayOfMonth = new \DateTime('first day of this month midnight');
        $qb              = $this->createQueryBuilder('pbl');

        $qb
            ->select('count(pbl.id)')
            ->join('pbl.user', 'ui')

            ->where('ui = :user')
            ->andWhere('pbl.created_at > :date')
            ->andWhere('pbl.pro = false')
            ->andWhere('pbl.bid is not null')

            ->setParameter('date', $firstDayOfMonth)
            ->setParameter('user', $user)
        ;

        try {
            $count = (int) $qb->getQuery()->getSingleScalarResult();
            return $count;
        } catch (QueryException $e) {
            return null;
        }
    }
}
