<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserVocalCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVocalCharacteristicRepository extends EntityRepository
{
    /**
     * Get vocal charactistic ids for user
     *
     * @param int $userInfoId
     *
     * @return array
     */
    public function getVocalCharacteristicIdsForUser($userInfoId)
    {
        $q = $this->createQueryBuilder('uvc')
                ->select('uvc.id, vc.id as vocal_id')
                ->innerJoin('uvc.vocal_characteristic', 'vc')
                ->where('uvc.user_info = :userInfoId');
        $params = [
            ':userInfoId' => $userInfoId,
        ];
        $q->setParameters($params);

        if ($results = $q->getQuery()->getArrayResult()) {
            $newResults = [];
            foreach ($results as $result) {
                $newResults[$result['id']] = $result['vocal_id'];
            }
            return $newResults;
        }
        return [];
    }

    /**
     * Get user vocal characteristics and join voted from
     *
     * @param int $userInfoId
     * @param int $fromUserInfoId
     */
    public function getByUserJoinVotedUser($userInfoId, $fromUserInfoId)
    {
        $q = $this->createQueryBuilder('uvc')
                ->select('uvc, vc')
                ->innerJoin('uvc.vocal_characteristic', 'vc')
                ->where('uvc.user_info = :userInfoId');

        $params = [
            ':userInfoId' => $userInfoId,
        ];
        if ($fromUserInfoId) {
            $q->addSelect('uvcv');
            $q->leftJoin(
                'uvc.user_vocal_characteristic_votes',
                'uvcv',
                'WITH',
                'uvcv.from_user_info = :fromUserInfoId'
            );
            $params[':fromUserInfoId'] = $fromUserInfoId;
        }

        $q->setParameters($params);
        $query = $q->getQuery();

        return $query->execute();
    }

    /**
     * Get single user vocal characteristic by id and join voted
     *
     * @param int $id
     * @param int $fromUserInfoId
     *
     * @return UserVocalCharacteristic|null
     */
    public function getByIdJoinVotedUser($id, $fromUserInfoId = null)
    {
        $q = $this->createQueryBuilder('uvc')
                ->select('uvc, vc')
                ->innerJoin('uvc.vocal_characteristic', 'vc')
                ->where('uvc.id = :id');

        $params = [
            ':id' => $id,
        ];

        if ($fromUserInfoId) {
            $q->addSelect('uvcv');
            $q->leftJoin(
                'uvc.user_vocal_characteristic_votes',
                'uvcv',
                'WITH',
                'uvcv.from_user_info = :fromUserInfoId'
            );
            $params[':fromUserInfoId'] = $fromUserInfoId;
        }

        $q->setParameters($params);
        $query = $q->getQuery();

        try {
            return $query->getOneOrNullResult();
        } catch (Doctrine\ORM\NonUniqueResultException $e) {
            return null;
        }
    }
}