<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Vocalizr\AppBundle\Entity\UserInfo;
use Vocalizr\AppBundle\Entity\UserWalletTransaction;

/**
 * UserWalletTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWalletTransactionRepository extends EntityRepository
{
    /**
     * @param string   $type
     * @param UserInfo $user
     *
     * @return UserWalletTransaction|null
     */
    public function findLastByTypeAndUser($type, UserInfo $user)
    {
        $qb = $this->createQueryBuilder('uwt');

        $qb
            ->where('uwt.user_info = :user')
            ->andWhere('uwt.type = :type')

            ->orderBy('uwt.created_at', 'DESC')

            ->setMaxResults(1)

            ->setParameters([
                'user' => $user,
                'type' => $type,
            ])
        ;

        try {
            $transaction = $qb->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
            $transaction = null;
        }

        return $transaction;
    }

    /**
     * @param int|UserInfo $user
     *
     * @return UserWalletTransaction[]
     */
    public function findTransactionsByUser($user)
    {
        return $this->findTransactionsByUserQb($user)->getQuery()->getResult();
    }

    /**
     * @param int|UserInfo $user
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findTransactionsByUserQb($user)
    {
        $qb = $this->createQueryBuilder('s');
        $qb
            ->where('s.user_info = :user')

            ->orderBy('s.created_at', 'DESC')
            ->addOrderBy('s.id', 'DESC')

            ->setParameter(':user', $user)
        ;

        return $qb;
    }

    /**
     * @param $type
     * @param UserInfo $user
     * @return UserWalletTransaction[]
     */
    public function findTransactionsByTypeAndUser($type, UserInfo $user)
    {
        $qb = $this->createQueryBuilder('uwt');
        $qb
            ->andWhere('uwt.user_info = :user')
            ->andWhere('uwt.type = :type')

            ->orderBy('uwt.created_at', 'DESC')

            ->setParameters([
                'user' => $user,
                'type' => $type,
            ])
        ;
        return $qb->getQuery()->getResult();
    }


    /**
     * @param $txnId
     * @param UserInfo|null $user
     * @return UserWalletTransaction[]
     */
    public function findTransactionsAfterId($txnId, $user = null)
    {
        $qb = $this->createQueryBuilder('uwt');
        $qb
            ->andWhere('uwt.id > :id')
            ->setParameter('id', $txnId)

            ->addOrderBy('uwt.id', 'ASC')
            ;
        if ($user) {
            $qb
                ->andWhere('uwt.user_info = :user')
                ->setParameter('user', $user)
                ;
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * @param array|string $customId
     * @return UserWalletTransaction|null
     */
    public function findByCustomId($customId)
    {
        $qb = $this->createQueryBuilder('uwt');

        if (is_array($customId)) {
            $qb
                ->andWhere('uwt.custom_id IN (:customId)')
                ;
        } else {
            $qb
                ->andWhere('uwt.custom_id = :customId')
                ;
        }
        $qb
            ->setParameter('customId', $customId)
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findCommissionsCurrentMonth()
    {
        $dateEnd = new \DateTime('now');
        $dateStart = new \DateTime('-'.($dateEnd->format('d') - 1).' day midnight');

        $qb = $this->createQueryBuilder('uwt')
            ->andWhere('uwt.created_at between :dateStart and :dateEnd')
            ->andWhere('uwt.description like :fee OR uwt.description like :feeContest OR uwt.description like :feeNew')
            ->setParameter('dateStart', $dateStart)
            ->setParameter('dateEnd', $dateEnd)
            ->setParameter('fee', 'Gig fee taken%')
            ->setParameter('feeContest', 'Contest fee taken for%')
            ->setParameter('feeNew', 'Platform commission fee for%')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findJobUpgradesCurrentMonth()
    {
        $dateEnd = new \DateTime('now');
        $dateStart = new \DateTime('-'.($dateEnd->format('d') - 1).' day midnight');

        $qb = $this->createQueryBuilder('uwt')
            ->andWhere('uwt.created_at between :dateStart and :dateEnd')
            ->andWhere('uwt.description like :job')
            ->setParameter('dateStart', $dateStart)
            ->setParameter('dateEnd', $dateEnd)
            ->setParameter('job', 'Upgrade charges for%')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findJobUpgradesAllTime()
    {
        $qb = $this->createQueryBuilder('uwt')
            ->andWhere('uwt.description like :job')
            ->setParameter('job', 'Upgrade charges for%')
        ;

        return $qb->getQuery()->getResult();
    }

    public function findCommissionsAllTime()
    {
        $qb = $this->createQueryBuilder('uwt')
            ->andWhere('uwt.description like :fee OR uwt.description like :feeContest OR uwt.description like :feeNew')
            ->setParameter('fee', 'Gig fee taken%')
            ->setParameter('feeContest', 'Contest fee taken for%')
            ->setParameter('feeNew', 'Platform commission fee for%')
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @param $year
     * @param $quarter
     */
    public function findGigCommissionsByYearAndQuarter($year, $quarter)
    {
        $quarterDate = [
            1 => ['startMonth' => 1, 'startDay' => 1, 'endMonth' => 3, 'endDay' => 31],
            2 => ['startMonth' => 4, 'startDay' => 1, 'endMonth' => 6, 'endDay' => 30],
            3 => ['startMonth' => 7, 'startDay' => 1, 'endMonth' => 9, 'endDay' => 30],
            4 => ['startMonth' => 10, 'startDay' => 1, 'endMonth' => 12, 'endDay' => 31]
        ];
        $dateStart = new \DateTime();
        $dateStart->setDate($year, $quarterDate[$quarter]['startMonth'], $quarterDate[$quarter]['startDay']);
        $dateEnd = new \DateTime();
        $dateEnd->setDate($year, $quarterDate[$quarter]['endMonth'], $quarterDate[$quarter]['endDay']);
        $qb = $this->createQueryBuilder('uwt')
            ->select('sum(uwt.amount)')
            ->leftJoin('uwt.user_info', 'ui')
            ->andWhere('uwt.created_at between :dateStart and :dateEnd')
            ->andWhere('uwt.description LIKE :gigFee')
            ->andWhere('ui.country = :country')
            ->setParameter('dateStart', $dateStart)
            ->setParameter('dateEnd', $dateEnd)
            ->setParameter('gigFee', 'Gig fee taken%')
            ->setParameter('country', 'AU')
        ;

        return -$qb->getQuery()->getSingleScalarResult() / 100;
    }

    /**
     * @param $year
     * @param $quarter
     */
    public function findUpgradesByYearAndQuarter($year, $quarter)
    {
        $quarterDate = [
            1 => ['startMonth' => 1, 'startDay' => 1, 'endMonth' => 3, 'endDay' => 31],
            2 => ['startMonth' => 4, 'startDay' => 1, 'endMonth' => 6, 'endDay' => 30],
            3 => ['startMonth' => 7, 'startDay' => 1, 'endMonth' => 9, 'endDay' => 30],
            4 => ['startMonth' => 10, 'startDay' => 1, 'endMonth' => 12, 'endDay' => 31]
        ];
        $dateStart = new \DateTime();
        $dateStart->setDate($year, $quarterDate[$quarter]['startMonth'], $quarterDate[$quarter]['startDay']);
        $dateEnd = new \DateTime();
        $dateEnd->setDate($year, $quarterDate[$quarter]['endMonth'], $quarterDate[$quarter]['endDay']);
        $qb = $this->createQueryBuilder('uwt')
            ->select('sum(uwt.amount)')
            ->leftJoin('uwt.user_info', 'ui')
            ->andWhere('uwt.created_at between :dateStart and :dateEnd')
            ->andWhere('uwt.description LIKE :gigFee')
            ->andWhere('ui.country = :country')
            ->setParameter('dateStart', $dateStart)
            ->setParameter('dateEnd', $dateEnd)
            ->setParameter('gigFee', 'Upgrade charges for%')
            ->setParameter('country', 'AU')
        ;

        return -$qb->getQuery()->getSingleScalarResult() / 100;
    }

    public function findYearsWithRecords()
    {
        $qb = $this->createQueryBuilder('uwt')
            ->select('date_format(uwt.created_at, \'%Y\') as year')
            ->leftJoin('uwt.user_info', 'ui')
            ->andWhere('uwt.description LIKE :gigFee')
            ->andWhere('ui.country = :country')
            ->setParameter('gigFee', 'Gig fee taken%')
            ->setParameter('country', 'AU')
            ->groupBy('year')

        ;

        return $qb->getQuery()->getResult();
    }
}
