<?php

namespace Vocalizr\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBlockRepository extends EntityRepository
{
    /**
     * Check if user is a favorite or not
     *
     * @param int $userInfoId
     */
    public function isUserBlocked($userInfo, $blockUserInfo)
    {
        $q = $this->createQueryBuilder('ub')
                ->select('count(ub.id)')
                ->where('ub.user_info = :userInfo AND ub.block_user = :blockUserInfo');

        $params = [
            ':userInfo'      => $userInfo,
            ':blockUserInfo' => $blockUserInfo,
        ];
        $q->setParameters($params);

        $query = $q->getQuery();

        return $query->getSingleScalarResult();
    }
}
