<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCommentRepository extends EntityRepository
{
}
