<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectLyricsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectLyricsRepository extends EntityRepository
{
    /**
     * Get lyrics by project id
     *
     * @param int $projectId
     *
     * @return array
     */
    public function getLyrics($projectId)
    {
        $q = $this->createQueryBuilder('pl')
                ->select('pl, ui')
                ->innerJoin('pl.user_info', 'ui')
                ->where('pl.project = :projectId')
                ->orderBy('pl.created_at', 'DESC')
                ->setParameter(':projectId', $projectId);
        $query = $q->getQuery();

        return $query->execute();
    }
}
