<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use App\Entity\UserInfo;

/**
 * UserReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserReviewRepository extends EntityRepository
{
    /**
     * @param UserInfo $userInfo
     *
     * @return QueryBuilder
     */
    public function getUserReviewsQb(UserInfo $userInfo)
    {
        return $this->createQueryBuilder('ur')
            ->select('ur, rb')
            ->innerJoin('ur.reviewed_by', 'rb')
            ->where('ur.user_info = :userInfoId and ur.hide = 0')
            ->orderBy('ur.created_at', 'DESC')
            ->setParameter(':userInfoId', $userInfo->getId());
    }

    /**
     * @param UserInfo $userInfo
     * @return int
     */
    public function getUserReviewsCount(UserInfo $userInfo)
    {
        $qb = $this->getUserReviewsQb($userInfo);
        $qb
            ->select($qb->expr()->count('ur.id'))
        ;

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * @param UserInfo $user
     * @param string $type
     *
     * @return QueryBuilder
     */
    public function getUserReviewsByTypeQb(UserInfo $user, $type)
    {
        return $this->getUserReviewsQb($user)
            ->andWhere('ur.type = :review_type')
            ->setParameter('review_type', $type)
        ;
    }
}
