<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserPrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPrefRepository extends EntityRepository
{
}
