<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserVocalCharacteristicVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserVocalCharacteristicVoteRepository extends EntityRepository
{
}
