<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VocalStyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocalStyleRepository extends EntityRepository
{
    /**
     * Get vocal stlyes for user
     *
     * @param int $userInfoId
     *
     * @return ArrayCollection
     */
    public function getByUserInfoId($userInfoId)
    {
        $q = $this->createQueryBuilder('vs')
                ->innerJoin('vs.user_vocal_styles', 'uvs')
                ->where('uvs.user_info = :userInfoId');
        $params = [
            ':userInfoId' => $userInfoId,
        ];
        $q->setParameters($params);
        $query = $q->getQuery();

        return $query->execute();
    }

    public function getAll()
    {
        $qb = $this->createQueryBuilder('vs')
                ->orderBy('vs.title', 'ASC');
        $query = $qb->getQuery();
        $query->useResultCache(true, 86400, 'vocalSTyles');
        $query->useQueryCache(true);
        $results = $query->execute();

        return $results;
    }
}
