<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VocalCharacteristicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VocalCharacteristicRepository extends EntityRepository
{
    /**
     * Get vocal characteristics for user
     *
     * @param int $userInfoId
     *
     * @return ArrayCollection
     */
    public function getByUserInfoId($userInfoId)
    {
        $q = $this->createQueryBuilder('vc')
                ->innerJoin('vc.user_vocal_characteristics', 'uvc')
                ->where('uvc.user_info = :userInfoId');
        $params = [
            ':userInfoId' => $userInfoId,
        ];
        $q->setParameters($params);
        $query = $q->getQuery();

        return $query->execute();
    }

    public function getAll()
    {
        $qb = $this->createQueryBuilder('vc')
                ->orderBy('vc.title', 'ASC');
        $query = $qb->getQuery();
        $query->useResultCache(true, 86400, 'vocalChars');
        $query->useQueryCache(true);
        $results = $query->execute();

        return $results;
    }
}
