<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoiceTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoiceTagRepository extends EntityRepository
{
    /**
     * Case insensitive findOneByName
     *
     * @param string $name
     *
     * @return array
     */
    public function findOneByName($name)
    {
        $q = $this->createQueryBuilder('vt')
                ->where('UPPER(vt.name) = :name');
        $q->setParameter(':name', strtoupper($name));

        $query = $q->getQuery();

        $results = $query->execute();

        if (!$results) {
            return null;
        }
        return $results[0];
    }
}
